/**
 * Permanent Real PostgreSQL Citizen Report Store Suite
 * ====================================================
 * Verifies PostgresCitizenReportStore against live PostgreSQL database:
 * 1. Insert report with full schema metadata
 * 2. Fetch by ID
 * 3. Isolation of PENDING reports
 * 4. State transition to APPROVED and visibility in listApprovedReports
 * 5. State transition to REJECTED and hiding from listApprovedReports
 * 6. Cryptographic duplicate-hash lookup
 * 7. Retention cleanup of aged rejected reports
 * 8. Schema check constraint violations (status, coordinates, category)
 */

import pg from 'pg';
import { PostgresCitizenReportStore, normalizeDatabaseUrl } from '../src/server/storage/reportStore';
import { prepareTestDatabase, truncateTestDatabase } from '../src/server/db/testDbHelper';

process.env.NODE_ENV = 'test';

let passed = 0;
let failed = 0;

function assert(condition: boolean, message: string) {
  if (condition) {
    passed++;
    console.log(`  ✓ ${message}`);
  } else {
    failed++;
    console.error(`  ✗ FAIL: ${message}`);
  }
}

async function runRealPostgresSuite() {
  console.log('================================================================');
  console.log('REAL POSTGRESQL CITIZEN REPORT STORE SUITE');
  console.log('================================================================\n');

  // Prepare test database: strictly validates TEST_DATABASE_URL (no fallback to DATABASE_URL),
  // verifies DB ends in "_test" and != dev DB, executes migrations, and truncates tables.
  const { testDbUrl, testDbName } = await prepareTestDatabase();
  console.log(`Connecting strictly to isolated test database: "${testDbName}"\n`);

  const store = new PostgresCitizenReportStore(testDbUrl);
  const normalizedUrl = normalizeDatabaseUrl(testDbUrl);
  const rawClient = new pg.Client({ connectionString: normalizedUrl });
  await rawClient.connect();

  const testReportIds: string[] = [];

  try {
    // -------------------------------------------------------------------------
    // 1. Insert report with full schema metadata
    // -------------------------------------------------------------------------
    console.log('TEST 1: Insert Report into PostgreSQL');
    const inserted = await store.insertReport({
      category: 'smoke',
      description: 'Dense black smoke near industrial zone',
      lat: 28.6139,
      lon: 77.209,
      nearest_station_id: 'DL001',
      nearest_station_name: 'Anand Vihar, Delhi - DPCC',
      nearest_station_distance_km: 1.8,
      image_key: 'pg_live_img_001.jpg',
      thumb_key: 'pg_live_thumb_001.jpg',
      content_hash: 'sha256_live_real_db_test_hash_001',
      client_timestamp: new Date().toISOString(),
    });

    testReportIds.push(inserted.id);
    assert(typeof inserted.id === 'string' && inserted.id.length === 36, 'UUID primary key generated by PostgreSQL');
    assert(inserted.status === 'PENDING', 'Initial status set strictly to PENDING');
    assert(inserted.nearest_station_name === 'Anand Vihar, Delhi - DPCC', 'Station name persisted');
    assert(inserted.nearest_station_distance_km === 1.8, 'Nearest station distance persisted');

    // -------------------------------------------------------------------------
    // 2. Fetch by ID
    // -------------------------------------------------------------------------
    console.log('\nTEST 2: Fetch Report by ID');
    const fetched = await store.getReportById(inserted.id);
    assert(fetched !== null, 'Report fetched back by ID');
    assert(fetched?.description === 'Dense black smoke near industrial zone', 'Description matches exactly');
    assert(fetched?.content_hash === 'sha256_live_real_db_test_hash_001', 'Content hash matches');

    // -------------------------------------------------------------------------
    // 3. PENDING Isolation from Public Approved Queries
    // -------------------------------------------------------------------------
    console.log('\nTEST 3: PENDING Isolation from Public Queries');
    const approvedBefore = await store.listApprovedReports();
    const foundPending = approvedBefore.reports.some((r) => r.id === inserted.id);
    assert(!foundPending, 'PENDING report is strictly excluded from listApprovedReports');

    // -------------------------------------------------------------------------
    // 4. State Transition to APPROVED
    // -------------------------------------------------------------------------
    console.log('\nTEST 4: Transition Status to APPROVED');
    const approved = await store.updateReportStatus(inserted.id, 'APPROVED');
    assert(approved !== null && approved.status === 'APPROVED', 'Report status updated to APPROVED');
    assert(approved?.moderated_at !== null, 'moderated_at timestamp populated');

    const approvedAfter = await store.listApprovedReports();
    const foundApproved = approvedAfter.reports.some((r) => r.id === inserted.id);
    assert(foundApproved, 'Approved report is now visible in listApprovedReports');

    // -------------------------------------------------------------------------
    // 5. State Transition to REJECTED with Reason
    // -------------------------------------------------------------------------
    console.log('\nTEST 5: Transition Status to REJECTED');
    const rejected = await store.updateReportStatus(inserted.id, 'REJECTED', 'Low visibility photo');
    assert(rejected !== null && rejected.status === 'REJECTED', 'Report status updated to REJECTED');
    assert(rejected?.moderation_reason === 'Low visibility photo', 'Moderation reason recorded');

    const approvedAfterReject = await store.listApprovedReports();
    const foundRejected = approvedAfterReject.reports.some((r) => r.id === inserted.id);
    assert(!foundRejected, 'REJECTED report is immediately excluded from listApprovedReports');

    // -------------------------------------------------------------------------
    // 6. Cryptographic Duplicate-Hash Lookup
    // -------------------------------------------------------------------------
    console.log('\nTEST 6: Duplicate Content Hash Detection');
    const duplicateMatch = await store.findRecentDuplicateHash('sha256_live_real_db_test_hash_001', 24);
    assert(duplicateMatch !== null && duplicateMatch.id === inserted.id, 'Detected recent duplicate hash in PostgreSQL');

    const noDuplicate = await store.findRecentDuplicateHash('sha256_non_existent_hash', 24);
    assert(noDuplicate === null, 'Returns null for non-duplicate hash');

    // -------------------------------------------------------------------------
    // 7. Image Key Lookup
    // -------------------------------------------------------------------------
    console.log('\nTEST 7: Image Key & Thumbnail Key Lookup');
    const byImg = await store.getReportByImageKey('pg_live_img_001.jpg');
    assert(byImg !== null && byImg.id === inserted.id, 'Found report by main image key');
    const byThumb = await store.getReportByImageKey('pg_live_thumb_001.jpg');
    assert(byThumb !== null && byThumb.id === inserted.id, 'Found report by thumbnail key');

    // -------------------------------------------------------------------------
    // 8. Retention Cleanup of Rejected Reports
    // -------------------------------------------------------------------------
    console.log('\nTEST 8: Rejected Reports Retention Cleanup');
    // Set moderated_at to 10 days ago
    await rawClient.query(
      "UPDATE citizen_reports SET moderated_at = NOW() - INTERVAL '10 days' WHERE id = $1;",
      [inserted.id]
    );

    const cleanupResult = await store.cleanupRejectedReports(7);
    assert(cleanupResult.deletedCount >= 1, 'Cleaned up expired rejected reports');
    assert(cleanupResult.deletedKeys.includes('pg_live_img_001.jpg'), 'Expired image key returned for file deletion');

    const fetchedAfterCleanup = await store.getReportById(inserted.id);
    assert(fetchedAfterCleanup === null, 'Report permanently deleted from database after retention window');

    // -------------------------------------------------------------------------
    // 9. Schema Constraint Violations
    // -------------------------------------------------------------------------
    console.log('\nTEST 9: Schema Check Constraints (Server-Side DB Integrity)');

    // 9a. Invalid status constraint
    let statusFailed = false;
    try {
      await rawClient.query(
        "INSERT INTO citizen_reports (category, lat, lon, image_key, thumb_key, content_hash, status) VALUES ('smoke', 28.0, 77.0, 'a.jpg', 'b.jpg', 'h', 'INVALID_STATUS');"
      );
    } catch {
      statusFailed = true;
    }
    assert(statusFailed, 'PostgreSQL check constraint strictly rejects invalid status');

    // 9b. Invalid latitude constraint (> 90.0)
    let latFailed = false;
    try {
      await rawClient.query(
        "INSERT INTO citizen_reports (category, lat, lon, image_key, thumb_key, content_hash, status) VALUES ('smoke', 95.0, 77.0, 'a.jpg', 'b.jpg', 'h', 'PENDING');"
      );
    } catch {
      latFailed = true;
    }
    assert(latFailed, 'PostgreSQL check constraint strictly rejects latitude > 90.0');

    // 9c. Invalid category constraint
    let catFailed = false;
    try {
      await rawClient.query(
        "INSERT INTO citizen_reports (category, lat, lon, image_key, thumb_key, content_hash, status) VALUES ('malicious_category', 28.0, 77.0, 'a.jpg', 'b.jpg', 'h', 'PENDING');"
      );
    } catch {
      catFailed = true;
    }
    assert(catFailed, 'PostgreSQL check constraint strictly rejects unauthorized category');
  } finally {
    // Truncate only the test database tables
    try {
      await truncateTestDatabase(testDbUrl);
    } catch {}
    await rawClient.end();
  }

  console.log('\n----------------------------------------------------------------');
  console.log(`POSTGRESQL SUITE: TOTAL: ${passed + failed} | PASSED: ${passed} | FAILED: ${failed}`);
  console.log('----------------------------------------------------------------\n');

  if (failed > 0) {
    process.exit(1);
  }
}

runRealPostgresSuite().catch((err) => {
  console.error('Fatal Postgres Suite Error:', err);
  process.exit(1);
});
